services:
  api:
    build:
      context: ./src
      target: builder
    container_name: fastapi-application
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    environment:
      PORT: 8000    
      DATABASE_URL: postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    volumes:
      - ./src/:/src/app/
    ports:
      - 8002:8000
    restart: "no"
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:./src/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_USER: hello_fastapi
      POSTGRES_PASSWORD: hello_fastapi
      POSTGRES_DB: hello_fastapi_dev

volumes:
  postgres_data: